name: å‘å¸ƒç‰ˆæœ¬

on:
  workflow_call:
    inputs:
      run_id:
        description: 'Get RunID'
        required: true
        type: string
  push:
    tags:
      - 'release:*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: zip
          run_id: ${{ inputs.run_id }}

      - name: Get Version
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_OUTPUT

      - name: Init Changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: |
            exclude:
              labels:
                - 'skip-changelog'
            categories:
              - title: 'ğŸš€ æ–°åŠŸèƒ½'
                labels:
                  - 'feat'
                  - 'feature'
                  - 'enhancement'
              - title: 'ğŸ› Bugä¿®å¤'
                labels:
                  - 'bug'
                  - 'fix'
              - title: 'ğŸ“š æ–‡æ¡£æ›´æ–°'
                labels:
                  - 'docs'
              - title: 'ğŸ”§ å…¶ä»–'
                labels:
                  - 'chore'
              - title: 'ğŸ”§ é‡æ„'
                labels:
                  - 'refactor'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release/${{ steps.get_version.outputs.version }}
          name: ç‰ˆæœ¬ ${{ steps.get_version.outputs.version }}
          body: ${{ steps.init-changelog.outputs.changelog }}
          prerelease: false
          draft: false
          files: |
            zip/ClassManager_latest_Windows-x64.zip