name: å‘å¸ƒç‰ˆæœ¬

on:
  workflow_call:
    inputs:
      run_id:
        description: 'Get RunID'
        required: true
        type: string
  push:
    tags:
      - 'release/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: zip
          run_id: ${{ inputs.run_id }}

      - name: Get Version
        id: get_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/release/}" >> $GITHUB_OUTPUT

      - name: Init Changelog
        id: init_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: |
            template: |+
              ## æ›´æ–°æ—¥å¿— ğŸ‰
              {{ changelog }}
              **å®Œæ•´æ›´æ–°æ—¥å¿—**: {{releaseUrl}}
            commitMode: "angular"
            failOnError: false
            exclude:
              labels:
                - 'skip-changelog'
                - 'duplicate'
                - 'invalid'
            categories:
              - title: 'ğŸš€ æ–°åŠŸèƒ½'
                labels:
                  - 'feat'
                  - 'feature'
                  - 'enhancement'
              - title: 'ğŸ› Bugä¿®å¤'
                labels:
                  - 'bug'
                  - 'fix'
              - title: 'âš¡ æ€§èƒ½ä¼˜åŒ–'
                labels:
                  - 'perf'
                  - 'performance'
              - title: 'ğŸ’„ ç•Œé¢ä¼˜åŒ–'
                labels:
                  - 'style'
                  - 'ui'
              - title: 'ğŸ“š æ–‡æ¡£æ›´æ–°'
                labels:
                  - 'docs'
                  - 'documentation'
              - title: 'â™»ï¸ ä»£ç é‡æ„'
                labels:
                  - 'refactor'
              - title: 'ğŸ”§ å…¶ä»–æ›´æ–°'
                labels:
                  - 'chore'
                  - 'build'
                  - 'ci'
                  - 'test'
              - title: 'ğŸ”’ ç‰ˆæœ¬æ›´æ–°'
                labels:
                  - 'release'
                  - 'publish'
                  - 'update'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release/${{ steps.get_version.outputs.version }}
          name: ç‰ˆæœ¬ ${{ steps.get_version.outputs.version }}
          body: ${{ steps.init_changelog.outputs.changelog }}
          prerelease: false
          draft: false
          files: |
            zip/*.zip